# Generated by Django 6.0.5 on 2026-07-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(db_index=True),
        ),
    ]
