# Generated by Django 6.0.5 on 2026-07-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='activity_interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='challenges',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='degree_level',
            field=models.CharField(blank=True, choices=[('bachelors', "Bachelor's"), ('masters', "Master's"), ('phd', 'PhD'), ('language', 'Language Program'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='expected_graduation_year',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='housing_type',
            field=models.CharField(blank=True, choices=[('dormitory', 'Dormitory'), ('off_campus', 'Off-campus')], max_length=15),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='residence_area',
            field=models.CharField(blank=True, max_length=150, verbose_name='District/area of residence in Beijing'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='sponsorship_status',
            field=models.CharField(blank=True, choices=[('gov_scholarship', 'Government Scholarship'), ('chinese_gov_scholarship', 'Chinese Government Scholarship'), ('university_scholarship', 'University Scholarship'), ('self_sponsored', 'Self-Sponsored'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='suggestions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='wechat_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='WeChat ID'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='year_of_study',
            field=models.CharField(blank=True, choices=[('first', 'First Year'), ('second', 'Second Year'), ('third', 'Third Year'), ('fourth', 'Fourth Year'), ('fifth', 'Fifth Year'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(blank=True, max_length=150, verbose_name='Field of study'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Registered BULS member'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='university',
            field=models.CharField(blank=True, max_length=150, verbose_name='University name'),
        ),
    ]
