# Generated by Django 6.0.5 on 2026-07-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentprofile_activity_interests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
